export const SKILL_ENTRIES = [
  { label: 'Python', aliases: ['python'] },
  { label: 'JavaScript', aliases: ['javascript', 'js', 'ecmascript'] },
  { label: 'TypeScript', aliases: ['typescript', 'ts'] },
  { label: 'Java', aliases: ['java'] },
  { label: 'C++', aliases: ['c++'] },
  { label: 'C#', aliases: ['c#', 'csharp'] },
  { label: 'Go', aliases: ['go', 'golang'] },
  { label: 'Rust', aliases: ['rust'] },
  { label: 'Ruby', aliases: ['ruby'] },
  { label: 'PHP', aliases: ['php'] },
  { label: 'Swift', aliases: ['swift'] },
  { label: 'Kotlin', aliases: ['kotlin'] },
  { label: 'HTML', aliases: ['html'] },
  { label: 'CSS', aliases: ['css'] },
  { label: 'React', aliases: ['react', 'react.js', 'reactjs'] },
  { label: 'Angular', aliases: ['angular'] },
  { label: 'Vue', aliases: ['vue', 'vue.js', 'vuejs'] },
  { label: 'Node.js', aliases: ['node.js', 'nodejs', 'node'] },
  { label: 'Express', aliases: ['express', 'express.js'] },
  { label: 'Next.js', aliases: ['next.js', 'nextjs'] },
  { label: 'Nuxt', aliases: ['nuxt', 'nuxt.js'] },
  { label: 'Django', aliases: ['django'] },
  { label: 'Flask', aliases: ['flask'] },
  { label: 'FastAPI', aliases: ['fastapi'] },
  { label: 'Spring', aliases: ['spring', 'spring boot', 'springboot'] },
  { label: 'SQL', aliases: ['sql'] },
  { label: 'MySQL', aliases: ['mysql'] },
  { label: 'PostgreSQL', aliases: ['postgresql', 'postgres'] },
  { label: 'MongoDB', aliases: ['mongodb', 'mongo'] },
  { label: 'Redis', aliases: ['redis'] },
  { label: 'Oracle', aliases: ['oracle'] },
  { label: 'Elasticsearch', aliases: ['elasticsearch'] },
  { label: 'DynamoDB', aliases: ['dynamodb'] },
  { label: 'AWS', aliases: ['aws', 'amazon web services'] },
  { label: 'Azure', aliases: ['azure', 'microsoft azure'] },
  { label: 'GCP', aliases: ['gcp', 'google cloud', 'google cloud platform'] },
  { label: 'Docker', aliases: ['docker'] },
  { label: 'Kubernetes', aliases: ['kubernetes', 'k8s'] },
  { label: 'Jenkins', aliases: ['jenkins'] },
  { label: 'Terraform', aliases: ['terraform'] },
  { label: 'Ansible', aliases: ['ansible'] },
  { label: 'CI/CD', aliases: ['ci/cd', 'cicd'] },
  { label: 'Microservices', aliases: ['microservices', 'microservice'] },
  { label: 'REST API', aliases: ['rest api', 'rest', 'api'] },
  { label: 'GraphQL', aliases: ['graphql'] },
  { label: 'Git', aliases: ['git', 'github', 'gitlab'] },
  { label: 'Jira', aliases: ['jira'] },
  { label: 'Agile', aliases: ['agile'] },
  { label: 'Scrum', aliases: ['scrum'] },
  { label: 'Kanban', aliases: ['kanban'] },
  { label: 'Machine Learning', aliases: ['machine learning', 'ml'] },
  { label: 'Deep Learning', aliases: ['deep learning'] },
  { label: 'AI', aliases: ['ai', 'artificial intelligence'] },
  { label: 'NLP', aliases: ['nlp', 'natural language processing'] },
  { label: 'Pandas', aliases: ['pandas'] },
  { label: 'NumPy', aliases: ['numpy'] },
  { label: 'Spark', aliases: ['spark', 'apache spark'] },
  { label: 'Kafka', aliases: ['kafka', 'apache kafka'] },
  { label: 'Linux', aliases: ['linux'] },
  { label: 'Bash', aliases: ['bash', 'shell'] },
  { label: 'Leadership', aliases: ['leadership', 'led', 'manage', 'managed', 'mentored'] },
  { label: 'Communication', aliases: ['communication', 'communicate', 'collaboration'] },
  { label: 'Teamwork', aliases: ['teamwork', 'team', 'cross-functional'] },
  { label: 'Problem Solving', aliases: ['problem solving', 'troubleshooting', 'debugging'] },
  { label: 'Project Management', aliases: ['project management', 'pmo'] },
  { label: 'Tableau', aliases: ['tableau'] },
  { label: 'Power BI', aliases: ['power bi'] },
  { label: 'Excel', aliases: ['excel'] },
  { label: 'Security', aliases: ['security', 'oauth', 'jwt', 'ssl', 'encryption'] }
];

export const STOP_WORDS = new Set([
  'the','and','for','with','that','this','from','have','will','your','our','their','about','into','using','used','use','are','was','were','you','who','what','when','where','why','how','role','job','position','experience','skills','skill'
]);

export const DISPLAY_OVERRIDES = {
  js: 'JavaScript',
  ts: 'TypeScript',
  node: 'Node.js',
  nodejs: 'Node.js',
  reactjs: 'React',
  nextjs: 'Next.js',
  vuejs: 'Vue',
  cicd: 'CI/CD',
  ml: 'Machine Learning',
  ai: 'AI',
  k8s: 'Kubernetes',
  postgres: 'PostgreSQL',
  mongo: 'MongoDB'
};